INFO_NOT_AVAILABLE = "Information not available"

# ---------------- Key Metrics ----------------
key_metrics_list = [
    "Current Price", "Open", "Previous Close", "Day High", "Day Low",
    "Market Cap", "52-Week Low", "52-Week High", "EBITDA",
    "Debt to Equity", "Current Ratio", "Return on Equity", "Return on Assets",
    "Free Cashflow", "Net Profit Margin", "Operating Margin", "Gross Margin", 
    "Price to Sales", "EPS Forward"
]

# Mapping metrics to possible keys in info / fi / balance sheets
key_metric_mapping = {
    "Current Price": ["currentPrice", "lastPrice"],
    "Open": ["open", "regularMarketOpen"],
    "Previous Close": ["previousClose", "regularMarketPreviousClose"],
    "Day High": ["dayHigh", "regularMarketDayHigh"],
    "Day Low": ["dayLow", "regularMarketDayLow"],
    "Market Cap": ["marketCap"],
    "52-Week Low": ["fiftyTwoWeekLow"],
    "52-Week High": ["fiftyTwoWeekHigh"],
    "EBITDA": ["ebitda"],
    "Debt to Equity": ["debtToEquity", "totalDebt", "bookValue"],
    "Current Ratio": ["currentRatio", "totalCurrentAssets", "totalCurrentLiabilities"],
    "Return on Equity": ["returnOnEquity", "netIncomeToCommon", "bookValue"],
    "Return on Assets": ["returnOnAssets", "netIncomeToCommon", "totalAssets"],
    "Free Cashflow": ["freeCashflow", "operatingCashflow", "capitalExpenditures"],
    "Net Profit Margin": ["netProfitMargin", "netIncomeToCommon", "totalRevenue"],
    "Operating Margin": ["operatingMargins", "operatingIncome", "totalRevenue"],
    "Gross Margin": ["grossMargins", "grossProfits", "totalRevenue"],
    "Price to Sales": ["priceToSales", "marketCap", "totalRevenue"],
    "EPS Forward": ["epsForward", "netIncomeToCommon", "sharesOutstanding"]
}

# ---------------- Other Metrics ----------------
other_metrics_mapping = {
    "auditRisk": "Audit Risk",
    "boardRisk": "Board Risk",
    "compensationRisk": "Compensation Risk",
    "shareHolderRightsRisk": "Shareholder Rights Risk",
    "overallRisk": "Overall Risk",
    "priceHint": "Price Hint",
    "dividendRate": "Dividend Rate",
    "payoutRatio": "Payout Ratio",
    "regularMarketVolume": "Regular Market Volume",
    "averageDailyVolume10Day": "Average Daily Volume (10 Day)",
    "twoHundredDayAverage": "200 Day Average",
    "heldPercentInsiders": "Held Percent by Insiders",
    "lastDividendValue": "Last Dividend Value",
    "targetMeanPrice": "Target Mean Price",
    "totalCashPerShare": "Total Cash per Share",
    "quickRatio": "Quick Ratio",
    "operatingCashflow": "Operating Cashflow",
    "epsTrailingTwelveMonths": "EPS (Trailing 12M)",
    "priceEpsCurrentYear": "Price/EPS Current Year",
    "fiveYearAvgDividendYield": "5Y Avg Dividend Yield",
    "forwardPE": "Forward PE",
    "averageVolume": "Average Volume",
    "priceToSalesTrailing12Months": "Price/Sales (TTM)",
    "floatShares": "Float Shares",
    "heldPercentInstitutions": "Held Percent by Institutions",
    "priceToBook": "Price to Book",
    "revenuePerShare": "Revenue per Share",
    "earningsGrowth": "Earnings Growth",
    "trailingPegRatio": "Trailing PEG Ratio",
    "allTimeHigh": "All Time High",
    "allTimeLow": "All Time Low",
    "fiftyTwoWeekLowChange": "52-Week Low Change",
    "fiftyTwoWeekLowChangePercent": "52-Week Low Change Percent",
    "fiftyTwoWeekRange": "52-Week Range",
    "fiftyTwoWeekHighChange": "52-Week High Change",
    "fiftyTwoWeekHighChangePercent": "52-Week High Change Percent",
    "fiftyTwoWeekChangePercent": "52-Week Change Percent",
    "epsCurrentYear": "EPS Current Year",
    "fiftyDayAverageChange": "50-Day Average Change",
    "fiftyDayAverageChangePercent": "50-Day Average Change Percent",
    "twoHundredDayAverageChange": "200-Day Average Change",
    "twoHundredDayAverageChangePercent": "200-Day Average Change Percent",
    "averageAnalystRating": "Average Analyst Rating",
    "cryptoTradeable": "Crypto Tradeable",
    "shares": "Shares",
    "tenDayAverageVolume": "10-Day Average Volume",
    "threeMonthAverageVolume": "3-Month Average Volume",
    "lastPrice": "Last Price",
    "lastVolume": "Last Volume",
    "yearChange": "Year Change",
    "yearHigh": "Year High",
    "yearLow": "Year Low",
    "beta": "Beta",
    "volume": "Volume",
    "averageVolume10days": "Average Volume (10 Days)",
    "fiftyDayAverage": "50 Day Average",
    "enterpriseValue": "Enterprise Value",
    "sharesOutstanding": "Shares Outstanding",
    "totalCash": "Total Cash",
    "revenueGrowth": "Revenue Growth",
}
