stock_categories = {
"Nifty 50": {
"Tata Consultancy Services (TCS)": "TCS.NS",
"Infosys": "INFY.NS",
"Reliance Industries": "RELIANCE.NS",
"HDFC Bank": "HDFCBANK.NS",
"ICICI Bank": "ICICIBANK.NS",
"State Bank of India": "SBIN.NS",
"Wipro": "WIPRO.NS",
"Hindustan Unilever": "HINDUNILVR.NS",
"Bharti Airtel": "BHARTIARTL.NS",
"Kotak Mahindra Bank": "KOTAKBANK.NS",
"Adani Enterprises": "ADANIENT.NS",
"Adani Ports & SEZ": "ADANIPORTS.NS",
"Apollo Hospitals": "APOLLOHOSP.NS",
"Asian Paints": "ASIANPAINT.NS",
"Axis Bank": "AXISBANK.NS",
"Bajaj Auto": "BAJAJ-AUTO.NS",
"Bajaj Finance": "BAJFINANCE.NS",
"Bajaj Finserv": "BAJAJFINSV.NS",
"Bharat Electronics": "BEL.NS",
"Cipla": "CIPLA.NS",
"Coal India": "COALINDIA.NS",
"Dr. Reddy's Laboratories": "DRREDDY.NS",
"Eicher Motors": "EICHERMOT.NS",
"Grasim Industries": "GRASIM.NS",
"HCLTech": "HCLTECH.NS",
"HDFC Life": "HDFCLIFE.NS",
"Hero MotoCorp": "HEROMOTOCO.NS",
"Hindalco Industries": "HINDALCO.NS",
"IndusInd Bank": "INDUSINDBK.NS",
"ITC": "ITC.NS",
"Jio Financial Services": "JIOFIN.NS",
"JSW Steel": "JSWSTEEL.NS",
"Larsen & Toubro": "LT.NS",
"Mahindra & Mahindra": "M&M.NS",
"Maruti Suzuki": "MARUTI.NS",
"Nestlé India": "NESTLEIND.NS",
"NTPC": "NTPC.NS",
"Oil and Natural Gas Corporation": "ONGC.NS",
"Power Grid": "POWERGRID.NS",
"SBI Life Insurance Company": "SBILIFE.NS",
"Shriram Finance": "SHRIRAMFIN.NS",
"Sun Pharma": "SUNPHARMA.NS",
"Tata Consumer Products": "TATACONSUM.NS",
"Tata Motors": "TATAMOTORS.NS",
"Tata Steel": "TATASTEEL.NS",
"Tech Mahindra": "TECHM.NS",
"Titan Company": "TITAN.NS",
"Trent": "TRENT.NS",
"UltraTech Cement": "ULTRACEMCO.NS"
},

"Bank Nifty": {
    "HDFC Bank Limited": "HDFCBANK.NS",
    "ICICI Bank Limited": "ICICIBANK.NS",
    "State Bank of India": "SBIN.NS",
    "Kotak Mahindra Bank Limited": "KOTAKBANK.NS",
    "Axis Bank Limited": "AXISBANK.NS",
    "Punjab National Bank": "PNB.NS",
    "Bank of Baroda": "BANKBARODA.NS",
    "Canara Bank": "CANBK.NS",
    "IndusInd Bank Ltd.": "INDUSINDBK.NS",
    "AU Small Finance Bank Limited": "AUBANK.NS",
    "IDFC First Bank Ltd.": "IDFCFIRSTB.NS",
    "Federal Bank Ltd. (India)": "FEDERALBNK.NS"
},

"Nifty Midcap 50": {
    "Aarti Industries Ltd.": "AARTIIND.NS",
    "ACC Ltd.": "ACC.NS",
    "Adani Power Ltd.": "ADANIPOWER.NS",
    "Aditya Birla Capital Ltd.": "ABCAPITAL.NS",
    "Alkem Laboratories Ltd.": "ALKEM.NS",
    "Ashok Leyland Ltd.": "ASHOKLEY.NS",
    "Au Small Finance Bank Ltd.": "AUBANK.NS",
    "Bajaj Holdings & Investment Ltd.": "BAJAJHLDNG.NS",
    "Balkrishna Industries Ltd.": "BALKRISIND.NS",
    "Bandhan Bank Ltd.": "BANDHANBNK.NS",
    "Bank of India": "BANKINDIA.NS",
    "Bata India Ltd.": "BATAINDIA.NS",
    "Bharat Forge Ltd.": "BHARATFORG.NS",
    "Bharat Heavy Electricals Ltd.": "BHEL.NS",
    "Canara Bank": "CANBK.NS",
    "Coforge Ltd.": "COFORGE.NS",
    "Container Corporation of India Ltd.": "CONCOR.NS",
    "Cummins India Ltd.": "CUMMINSIND.NS",
    "Dalmia Bharat Ltd.": "DALBHARAT.NS",
    "Dixon Technologies (India) Ltd.": "DIXON.NS",
    "Escorts Kubota Ltd.": "ESCORTS.NS",
    "Federal Bank Ltd.": "FEDERALBNK.NS",
    "Gland Pharma Ltd.": "GLAND.NS",
    "Godrej Properties Ltd.": "GODREJPROP.NS",
    "Gujarat Gas Ltd.": "GUJGASLTD.NS",
    "Hindustan Aeronautics Ltd.": "HAL.NS",
    "IDFC First Bank Ltd.": "IDFCFIRSTB.NS",
    "Indian Bank": "INDIANB.NS",
    "Indian Railway Catering & Tourism Corporation Ltd.": "IRCTC.NS",
    "Indraprastha Gas Ltd.": "IGL.NS",
    "Jindal Steel & Power Ltd.": "JINDALSTEL.NS",
    "JSW Energy Ltd.": "JSWENERGY.NS",
    "Jubilant Foodworks Ltd.": "JUBLFOOD.NS",
    "L&T Finance Holdings Ltd.": "L&TFH.NS",
    "Laurus Labs Ltd.": "LAURUSLABS.NS",
    "LIC Housing Finance Ltd.": "LICHSGFIN.NS",
    "Lupin Ltd.": "LUPIN.NS",
    "MRF Ltd.": "MRF.NS",
    "Max Financial Services Ltd.": "MFSL.NS",
    "MphasiS Ltd.": "MPHASIS.NS",
    "Navin Fluorine International Ltd.": "NAVINFLUOR.NS",
    "Oberoi Realty Ltd.": "OBEROIRLTY.NS",
    "Page Industries Ltd.": "PAGEIND.NS",
    "Persistent Systems Ltd.": "PERSISTENT.NS",
    "Petronet LNG Ltd.": "PETRONET.NS",
    "Polycab India Ltd.": "POLYCAB.NS",
    "Ramco Cements Ltd.": "RAMCOCEM.NS",
    "Tata Communications Ltd.": "TATACOMM.NS",
    "Tube Investments of India Ltd.": "TIINDIA.NS",
    "Vodafone Idea Ltd.": "IDEA.NS"
},

"Nifty Smallcap 250": {
    "3M India Limited": "3MINDIA.NS",
    "Aadhar Housing Finance Ltd": "AADHARHFC.NS",
    "Aarti Drugs Limited": "AARTIDRUGS.NS",
    "Aavas Financiers Limited": "AAVAS.NS",
    "ABB India Limited": "ABB.NS",
    "Aditya Birla Capital Limited": "ABCAPITAL.NS",
    "Aditya Birla Fashion and Retail Limited": "ABFRL.NS",
    "Aditya Birla Sun Life AMC Limited": "ABSLAMC.NS",
    "Aegis Logistics Limited": "AEGISLOG.NS",
    "Affle (India) Limited": "AFFLE.NS",
    "AIA Engineering Limited": "AIAENG.NS",
    "Ajanta Pharma Limited": "AJANTPHARM.NS",
    "Akzo Nobel India Limited": "AKZOINDIA.NS",
    "Alkyl Amines Chemicals Limited": "ALKYLAMINE.NS",
    "Amber Enterprises India Limited": "AMBER.NS",
    "Amrutanjan Health Care Limited": "AMRUTANJAN.NS",
    "Anant Raj Limited": "ANANTRAJ.NS",
    "Anand Rathi Wealth Limited": "ANANDRATHI.NS",
    "Angel One Limited": "ANGELONE.NS",
    "Apar Industries Limited": "APARIND.NS",
    "Apollo Hospitals Enterprise Limited": "APOLLOHOSP.NS",
    "Apollo Tyres Limited": "APOLLOTYRE.NS",
    "Archean Chemical Industries Limited": "ARCHEIAN.NS",
    "Arvind Limited": "ARVIND.NS",
    "Asahi India Glass Limited": "ASAHIINDIA.NS",
    "Ashima Limited": "ASHIMASYN.NS",
    "Aster DM Healthcare Limited": "ASTERDM.NS",
    "Astral Limited": "ASTRAL.NS",
    "Atul Limited": "ATUL.NS",
    "Authum Investment & Infrastructure Limited": "AIIL.NS",
    "Avantel Limited": "AVANTEL.NS",
    "Avenue Supermarts Limited": "DMART.NS",
    "Axis Bank Limited": "AXISBANK.NS",
    "Bajaj Electricals Limited": "BAJAJELEC.NS",
    "Bajaj Finance Limited": "BAJFINANCE.NS",
    "Bajaj Finserv Limited": "BAJAJFINSV.NS",
    "Bajaj Holdings & Investment Limited": "BAJAJHLDNG.NS",
    "Balaji Amines Limited": "BALAMINES.NS",
    "Balkrishna Industries Limited": "BALKRISIND.NS",
    "Balu Forge Industries Limited": "BALUFORGE.NS",
    "Banco Products (India) Limited": "BANCOINDIA.NS",
    "Bandhan Bank Limited": "BANDHANBNK.NS",
    "Bangalore Fort Farms Limited": "BENGALURUF.NS",
    "Bank of Baroda": "BANKBARODA.NS",
    "Bank of India": "BANKINDIA.NS",
    "Bannari Amman Sugars Limited": "BANARISUG.NS",
    "Barbeque Nation Hospitality Limited": "BARBEQUE.NS",
    "BASF India Limited": "BASF.NS",
    "Bata India Limited": "BATAINDIA.NS",
    "Bauddhik Web3 Labs Private Limited": "BAUDDHIK.NS",
    "Bayer Cropscience Limited": "BAYERCROP.NS",
    "BBTC Limited": "BBTC.NS",
    "Bekaert Desai Le Carbone India Limited": "BDL.NS",
    "BEML Limited": "BEML.NS",
    "Bengal & Assam Company Limited": "BENGALASSM.NS",
    "Bengal Tea & Fabrics Limited": "BENGATEA.NS",
    "Bharat Dynamics Limited": "BDL.NS",
    "Bharat Electronics Limited": "BEL.NS",
    "Bharat Heavy Electricals Limited": "BHEL.NS",
    "Bharat Petroleum Corporation Limited": "BPCL.NS",
    "Bharat Rasayan Limited": "BHARATRASAY.NS",
    "Bharat Wire Ropes Limited": "BHARATWIRE.NS",
    "Bharti Airtel Limited": "BHARTIARTL.NS",
    "Bhatia Colourchem Limited": "BATIACOLCH.NS",
    "BHEL Limited": "BHEL.NS",
    "Biocon Limited": "BIOCON.NS",
    "Birla Cable Limited": "BIRLACABLE.NS",
    "Birla Corporation Limited": "BIRLACORPN.NS",
    "Birlasoft Limited": "BSOFT.NS",
    "Blue Dart Express Limited": "BLUEDART.NS",
    "Blue Star Limited": "BLUESTARCO.NS",
    "Bombay Burmah Trading Corporation Limited": "BBTC.NS",
    "Borosil Limited": "BOROLTD.NS",
    "Borosil Renewables Limited": "BORORENEW.NS",
    "BPL Limited": "BPL.NS",
    "BPCL Limited": "BPCL.NS",
    "Brigade Enterprises Limited": "BRIGADE.NS",
    "Brightcom Group Limited": "BCG.NS",
    "BSE Limited": "BSE.NS",
    "BTL Industries Limited": "BTLIND.NS",
    "C.E. Info Systems Limited": "MAPMYINDIA.NS",
    "CESC Limited": "CESC.NS",
    "CG Power and Industrial Solutions Limited": "CGPOWER.NS",
    "CHALET HOTELS LIMITED": "CHALET.NS",
    "Chambal Fertilisers and Chemicals Limited": "CHAMBLFERT.NS",
    "Chandra Asri Pacific Tbk PT": "TPIA.JK",
    "Chennai Petroleum Corporation Limited": "CHENNPETRO.NS",
    "Cholamandalam Financial Holdings Limited": "CHOLAHLDNG.NS",
    "Cholamandalam Investment and Finance Company Limited": "CHOLAFIN.NS",
    "Cipla Limited": "CIPLA.NS",
    "City Union Bank Limited": "CUB.NS",
    "Clarus International Limited": "CLARUS.NS",
    "Coforge Limited": "COFORGE.NS",
    "Cognizant Technology Solutions Corporation": "CTSH.NS",
    "Colgate-Palmolive (India) Limited": "COLPAL.NS",
    "Computer Age Management Services Limited": "CAMS.NS",
    "Container Corporation of India Limited": "CONCOR.NS",
    "Coromandel International Limited": "COROMANDEL.NS",
    "Cummins India Limited": "CUMMINSIND.NS",
    "Cyient Limited": "CYIENT.NS",
    "D B Corp Limited": "DBCORP.NS",
    "Dalmia Bharat Limited": "DALBHARAT.NS",
    "Deloitte India Private Limited": "DEL01.NS",
    "Delphi-TVS Manufacturing Limited": "DELPHITVS.NS",
    "Delphix Corp": "DELPHIX.NS",
    "Delhivery Limited": "DELHIVERY.NS",
    "Deloitte": "DEL01.NS",
    "Dixon Technologies (India) Limited": "DIXON.NS",
    "Dr. Lal PathLabs Limited": "LALPATHLAB.NS",
    "Dr. Reddy's Laboratories Limited": "DRREDDY.NS",
    "Dreamfolks Services Limited": "DREAMFOLKS.NS",
    "Dredging Corporation of India Limited": "DREDGECORP.NS",
    "Dynamatic Technologies Limited": "DYNAMATECH.NS",
    "E.I.H. Limited": "EIHOTEL.NS",
    "E3 Corp Limited": "E3.NS",
    "EID-Parry (India) Limited": "EIDPARRY.NS",
    "EIH Associated Hotels Limited": "EIHASSO.NS",
    "Electrosteel Castings Limited": "ELECTCAST.NS",
    "Elecon Engineering Company Limited": "ELECON.NS",
    "Emami Limited": "EMAMI.NS",
    "Embassy Office Parks REIT": "EMBASSY.NS",
    "Emcure Pharmaceuticals Limited": "EMCURE.NS",
    "Emerson Electric Co.": "EMR.NS",
    "Equitas Small Finance Bank Limited": "EQUITASBNK.NS",
    "Esab India Limited": "ESABINDIA.NS",
    "Escorts Kubota Limited": "ESCORTS.NS",
    "Essar Shipping Ports and Logistics Limited": "ESSARSHPNG.NS",
    "Eveready Industries India Limited": "EVEREADY.NS",
    "Exide Industries Limited": "EXIDEIND.NS",
    "Fagun Limited": "FAGUN.NS",
    "Federal Bank Limited": "FEDERALBNK.NS",
    "Fertilisers and Chemicals Travancore Limited": "FACT.NS",
    "Fiem Industries Limited": "FIEMIND.NS",
    "Finolex Cables Limited": "FINCABLES.NS",
    "Finolex Industries Limited": "FINOLEX.NS",
    "Firstsource Solutions Limited": "FSL.NS",
    "FLEX LTD": "FLEX.NS",
    "Force Motors Limited": "FORCEMOT.NS",
    "Fortis Healthcare Limited": "FORTIS.NS",
    "Fountain Life Limited": "FOUNTAINL.NS",
    "G R Infraprojects Limited": "GRINFRA.NS",
    "GACL Edge Limited": "GACLE.NS",
    "Gail (India) Limited": "GAIL.NS",
    "Gallant Ispat Limited": "GALLANTT.NS",
    "Ganesh Housing Corp Limited": "GANESHHOUC.NS",
    "Garden Reach Shipbuilders & Engineers Limited": "GRSE.NS",
    "Garware Technical Fibres Limited": "GARFIBRES.NS",
    "Garware Hi-Tech Films Limited": "GARTECH.NS",
    "Geberit AG": "GEBN.SW",
    "Geojit Financial Services Limited": "GEOJITFSL.NS",
    "Gensol Engineering Limited": "GENSOL.NS",
    "GIC REIT": "GICREIT.NS",
    "Gillette India Limited": "GILLETTE.NS",
    "Gland Pharma Limited": "GLAND.NS",
    "Glenmark Life Sciences Limited": "GLENMARKLS.NS",
    "Glenmark Pharmaceuticals Limited": "GLENMARK.NS",
    "Global Health Limited": "MEDANTA.NS",
    "GMR Airports Infrastructure Limited": "GMRINFRA.NS",
    "GMR Power and Urban Infra Limited": "GMRP&U.NS",
    "Godawari Power & Ispat Limited": "GPIL.NS",
    "Godfrey Phillips India Limited": "GODFRYPHLP.NS",
    "Godrej Agrovet Limited": "GODREJAGRO.NS",
    "Godrej Consumer Products Limited": "GODREJCP.NS",
    "Godrej Industries Limited": "GODREJIND.NS",
    "Godrej Properties Limited": "GODREJPROP.NS",
    "Go Digit General Insurance Limited": "GODIGIT.NS",
    "Goa Carbon Limited": "GOACARBON.NS",
    "Gokaldas Exports Limited": "GOKEX.NS",
    "Goldiam International Limited": "GOLDIAM.NS",
    "Goodluck India Limited": "GOODLUCK.NS",
    "Gopal Snacks Limited": "GOPAL.NS",
    "Gore Street Energy Storage Fund Plc": "GSS.L",
    "Gottfried Wilhelm Leibniz Universität Hannover": "LUH.DE",
    "Grasim Industries Limited": "GRASIM.NS",
    "Great Eastern Shipping Company Limited": "GESHIP.NS",
    "Greaves Cotton Limited": "GREAVESCOT.NS",
    "Greenpanel Industries Limited": "GREENPANEL.NS",
    "Griffon Corporation": "GFF.NS",
    "Grindwell Norton Limited": "GRINDWELL.NS",
    "Gujarat Ambuja Exports Limited": "GAEL.NS",
    "Gujarat Fluorochemicals Limited": "FLUOROCHEM.NS",
    "Gujarat Gas Limited": "GUJGASLTD.NS",
    "Gujarat Mineral Development Corporation Limited": "GMDCLTD.NS",
    "Gujarat Narmada Valley Fertilizers & Chemicals Limited": "GNFC.NS",
    "Gujarat State Fertilizers & Chemicals Limited": "GSFC.NS",
    "Gujarat Toolroom Limited": "GTOOL.NS",
    "H.G. Infra Engineering Limited": "HGINFRA.NS",
    "Haldiram Snacks Food Private Limited": "HALDIRAM.NS",
    "Haldyn Glass Limited": "HALDYNGL.NS",
    "HDFC Asset Management Company Limited": "HDFCAMC.NS",
    "HDFC Bank Limited": "HDFCBANK.NS",
    "HDFC Life Insurance Company Limited": "HDFCLIFE.NS",
    "HDFC Sky": "SKY.NS",
    "HBL Power Systems Limited": "HBLPOWER.NS",
    "Healthium Medtech Limited": "HEALTHIUM.NS",
    "Hero MotoCorp Limited": "HEROMOTOCO.NS",
    "Hexaware Technologies Limited": "HEXAWARE.NS",
    "HFCL Limited": "HFCL.NS",
    "HG Infra Engineering Limited": "HGINFRA.NS",
    "High Energy Batteries (India) Limited": "HEBL.NS",
    "Himadri Speciality Chemical Limited": "HIMADRI.NS",
    "Hindalco Industries Limited": "HINDALCO.NS",
    "Hindustan Aeronautics Limited": "HAL.NS",
    "Hindustan Copper Limited": "HINDCOPPER.NS",
    "Hindustan Petroleum Corporation Limited": "HPCL.NS",
    "Hindustan Unilever Limited": "HINDUNILVR.NS",
    "Hindustan Zinc Limited": "HINDZINC.NS",
    "Honeywell Automation India Limited": "HONAUT.NS",
    "Horizon Robotics": "HRB.US",
    "Hospitals Limited": "HOSPITALS.NS",
    "Housing Development Finance Corporation Limited": "HDFC.NS",
    "Hov Services Limited": "HOVS.NS",
    "HUL Limited": "HINDUNILVR.NS",
    "ICICI Bank Limited": "ICICIBANK.NS",
    "ICICI Lombard General Insurance Company Limited": "ICICIGI.NS",
    "ICICI Prudential Life Insurance Company Limited": "ICICIPRULI.NS",
    "ICICI Securities Limited": "ISEC.NS",
    "IDBI Bank Limited": "IDBI.NS",
    "IDFC First Bank Limited": "IDFCFIRSTB.NS",
    "IFB Industries Limited": "IFBIND.NS",
    "IIFL Finance Limited": "IIFL.NS",
    "IIT Limited": "IITL.NS",
    "IITL Infra Tech Limited": "IITLINFRA.NS",
    "IndiGo": "INDIGO.NS",
    "Indian Bank": "INDIANB.NS",
    "Indian Energy Exchange Limited": "IEX.NS",
    "Indian Hotels Company Limited": "INDHOTEL.NS",
    "Indian Metals & Ferro Alloys Limited": "IMFA.NS",
    "Indian Oil Corporation Limited": "IOC.NS",
    "Indian Overseas Bank": "IOB.NS",
    "Indian Renewable Energy Development Agency Limited": "IREDA.NS",
    "Indo Count Industries Limited": "ICIL.NS",
    "Indo-Care": "INDOCARE.NS",
    "Indraprastha Gas Limited": "IGL.NS",
    "Indus Towers Limited": "INDUSTOWER.NS",
    "IndusInd Bank Limited": "INDUSINDBK.NS",
    "Inox Green Energy Services Limited": "INOXGREEN.NS",
    "Inox India Limited": "INOXINDIA.NS",
    "Inox Wind Limited": "INOXWIND.NS",
    "Inox Wind Energy Limited": "INOXWINDL.NS",
    "Inspired Education Group": "INSPIRED.NS",
    "Integra Essentia Limited": "INTEGRA.NS",
    "InterGlobe Aviation Limited": "INDIGO.NS",
    "International Gemmological Institute (India) Limited": "IGIL.NS",
    "Ion Exchange (India) Limited": "IONEXCHANG.NS",
    "IPCA Laboratories Limited": "IPCALAB.NS",
    "IRB Infrastructure Developers Limited": "IRB.NS",
    "IRCON International Limited": "IRCON.NS",
    "IRCTC": "IRCTC.NS",
    "ISGEC Heavy Engineering Limited": "ISGEC.NS",
    "ITD Cementation India Limited": "ITDLS.NS",
    "ITI Limited": "ITI.NS",
    "J Kumar Infraprojects Limited": "JKIL.NS",
    "J.B. Chemicals & Pharmaceuticals Limited": "JBCHEPHARM.NS",
    "J.K. Cement Limited": "JKCEMENT.NS",
    "J.M. Financial Limited": "JMFINANCIL.NS",
    "J.S. Wadia Group": "JSW.NS",
    "Jabil Inc.": "JBL.NS",
    "Jacobs Solutions Inc.": "J.NS",
    "Jagran Prakashan Limited": "JAGRAN.NS",
    "Jain Irrigation Systems Limited": "JISLJALEQS.NS",
    "Jamaica International Holdings Limited": "JIH.NS",
    "Jamco Corporation": "JAMCO.T",
    "Jana Small Finance Bank Limited": "JANA.NS",
    "Jaro Education Limited": "JARO.NS",
    "Jayaswal Neco Industries Limited": "JAYNECOIND.NS",
    "Jayshree Tea & Industries Limited": "JAYSREETEA.NS",
    "JB Chemicals & Pharmaceuticals Limited": "JBCHEPHARM.NS",
    "JBM Auto Limited": "JBMA.NS",
    "JBM Environment Infrastructure Limited": "JBME.NS",
    "JCKL Industries Limited": "JCKL.NS",
    "Jindal Poly Films Limited": "JINDPLASTF.NS",
    "Jindal Poly Investment and Finance Company Limited": "JPFINVEST.NS",
    "Jindal Saw Limited": "JINDALSAW.NS",
    "Jindal Stainless Limited": "JSL.NS",
    "Jindal Steel & Power Limited": "JINDALSTEL.NS",
    "Jindal Worldwide Limited": "JWL.NS",
    "JK Paper Limited": "JKPAPER.NS",
    "JK Tyre & Industries Limited": "JKTYRE.NS",
    "JMC Projects (India) Limited": "JMCPL.NS",
    "JMS Mining Private Limited": "JMSMINING.NS",
    "Jnana Prabodhini Institute of Psychology": "JPI.NS",
    "Jocil Limited": "JOCIL.NS",
    "Johannesburg Stock Exchange": "JSE.JO",
    "Johnson & Johnson": "JNJ.NS",
    "Johnson Controls-Hitachi Air Conditioning India Limited": "JCHAC.NS",
    "Jolly Professional Services Limited": "JOLLY.NS",
    "Jonas Software": "JONAS.NS",
    "Jubilant Bhartia Group": "JUBL.NS",
    "Jubilant FoodWorks Limited": "JUBLFOOD.NS",
    "Jubilant Ingrevia Limited": "JUBLINGREA.NS",
    "Jubilant Pharmova Limited": "JUBLPHARMA.NS",
    "Jyothy Labs Limited": "JYOTHYLAB.NS",
    "K.P.R. Mill Limited": "KPRMILL.NS",
    "K.S. Oils Limited": "KSOILS.NS",
    "Kaka Industries Limited": "KAKAIND.NS",
    "Kalpataru Projects International Limited": "KPIL.NS",
    "Kalyan Jewellers India Limited": "KALYANKJIL.NS",
    "Kama Holdings Limited": "KAMA.NS",
    "Kamal Distilleries & Industries Limited": "KDL.NS",
    "Kamataka Bank Limited": "KTKBANK.NS",
    "Kamdhenu Limited": "KAMDHENU.NS",
    "Kansai Nerolac Paints Limited": "KANSAINER.NS",
    "Kapil Raj Marble & Granite Private Limited": "KRMPG.NS",
    "Kappac Pharma Private Limited": "KAPPAC.NS",
    "Karara Mining Limited": "KARARA.AX",
    "Karur Vysya Bank Limited": "KARURVYSYA.NS",
    "Kasturi Housing and Resorts Limited": "KASTURI.NS",
    "Kaveri Seed Company Limited": "KSCL.NS",
    "Kaynes Technology India Limited": "KAYNES.NS",
    "KEC International Limited": "KEC.NS",
    "Kellton Tech Solutions Limited": "KELLTONTEC.NS",
    "Kemira Oyj": "KEMIRA.HE",
    "Kempegowda International Airport Limited": "KIAL.NS",
    "Kernex Microsystems (India) Limited": "KERNEX.NS",
    "Kesar Enterprises Limited": "KESAR.NS",
    "Kesar Petroproducts Limited": "KESARPETRO.NS",
    "Kettleborough Limited": "KETTLE.NS",
    "Kewal Kiran Clothing Limited": "KKCL.NS",
    "Kfin Technologies Limited": "KFINTECH.NS",
    "KGL Resources Limited": "KGL.AX",
    "Khandwala Securities Limited": "KSCLTD.NS",
    "Khivraj Motors Limited": "KHIVRAJ.NS",
    "Khyati Multimedia-Entertainment Limited": "KHYATI.NS",
    "Kilburn Engineering Limited": "KILBURN.NS",
    "Kimberly-Clark India Limited": "KIMBER.NS",
    "Kiran Vyapar Limited": "KIRANVYP.NS",
    "Kirloskar Brothers Limited": "KIRLOSBROS.NS",
    "Kirloskar Ferrous Industries Limited": "KIRLOSFERRO.NS",
    "Kirloskar Oil Engines Limited": "KIRLOSENG.NS",
    "Kirloskar Pneumatic Company Limited": "KIRLPNEU.NS",
    "Kirloskar Industries Limited": "KIRLOSIND.NS",
    "Kite Realty Group Trust": "KRG.NS",
    "KNR Constructions Limited": "KNRCON.NS",
    "Kopran Limited": "KOPRAN.NS",
    "Kotak Mahindra Bank Limited": "KOTAKBANK.NS",
    "Kothari Petrochemicals Limited": "KOTHARIPET.NS",
    "Kothari Products Limited": "KOTHARIPRO.NS",
    "Kraft Heinz Company (The)": "KHC.NS",
    "Krishana Phoschem Limited": "KRISHNAP.NS",
    "Krishna Institute of Medical Sciences Limited": "KIMS.NS",
    "Krishival Commodities DMCC": "KRISHIVAL.NS",
    "Kronox Lab Sciences Limited": "KRONOX.NS",
    "Kross Limited": "KROSS.NS",
    "KSB Limited": "KSB.NS",
    "KSRTC": "KSRTC.NS",
    "KSolves India Limited": "KSOLVES.NS",
    "Kuantum Papers Limited": "KUANTUM.NS",
    "Kubota Corporation": "KUBOTA.T",
    "Kudremukh Iron Ore Company Limited": "KIOCL.NS",
    "Kumho Petro Chemical Co Ltd": "KUMHO.T",
    "Kumudam Publications Private Limited": "KUMUDAM.NS",
    "Kurlon Limited": "KURLON.NS",
    "Kutumb": "KUTUMB.NS",
    "L&T Finance Holdings Limited": "LTF.NS",
    "L&T Technology Services Limited": "LTTS.NS",
    "Lakshmi Machine Works Limited": "LAXMIMACH.NS",
    "Lakshmi Mills Company Limited": "LAKSHMIM.NS",
    "Lakshmi Vilas Bank Limited": "LVBANK.NS",
    "Lanco Infratech Limited": "LITL.NS",
    "Landis+Gyr Group AG": "LANDI.SW",
    "Lange International S.A.": "LANGE.FR",
    "Larsen & Toubro Infotech Limited": "LTI.NS",
    "Larsen & Toubro Limited": "LT.NS",
    "Laurus Labs Limited": "LAURUSLABS.NS",
    "Laxmi Dental Limited": "LAXMIDEN.NS",
    "Laxmi Gypsum Co Limited": "LAXMIGYPS.NS",
    "Laxmi Organic Industries Limited": "LAXMIOILG.NS",
    "LCC Infotech Limited": "LCCINFOT.NS",
    "Le Meridien": "LEMERIDIEN.NS",
    "Le Travenues Limited": "IXIGO.NS",
    "Lead Squared": "LEADSQ.NS",
    "Legacy Lifetech Private Limited": "LEGACY.NS",
    "Lemon Tree Hotels Limited": "LEMONTREE.NS",
    "Lennox International Inc.": "LII.NS",
    "Liberty Shoes Limited": "LIBERTSHOE.NS",
    "LIC Housing Finance Limited": "LICHSGFIN.NS",
    "Life Insurance Corporation of India": "LICI.NS",
    "Likhitha Infrastructure Limited": "LIKHITHA.NS",
    "Linde India Limited": "LINDEINDIA.NS",
    "Lindstrom Group": "LINDSTROM.NS",
    "Linit": "LINIT.NS",
    "Lions": "LIONS.NS",
    "Lkp Finance Limited": "LKPF.NS",
    "Lloyd Metals and Energy Limited": "LLOYDSME.NS",
    "Loantap Financial Services Private Limited": "LOANTAP.NS",
    "Lodha Developers Limited": "LODHA.NS",
    "Lotte Chemical Corporation": "011170.KS",
    "Lotus Chocolate Company Limited": "LOTUSCHOCO.NS",
    "Lowell Farms Inc.": "LOWL.CN",
    "Loyal Equipments Limited": "LOYALEQUIP.NS",
    "Lupin Limited": "LUPIN.NS",
    "Lupine Energy Private Limited": "LUPINE.NS",
    "Luv Cushions Private Limited": "LUVCUSH.NS",
    "Lux Industries Limited": "LUXIND.NS",
    "M & M Limited": "M&M.NS",
    "M.R. PL. Limited": "MRPL.NS",
    "M3M India Limited": "M3M.NS",
    "Mac Hotels Limited": "MAC.NS",
    "Macrotech Developers Limited": "LODHA.NS",
    "Madras Fertilizers Limited": "MADRASFERT.NS",
    "Madras Rubber Factory Limited": "MRF.NS",
    "Mafatlal Industries Limited": "MAFATLAIND.NS",
    "Magna Electro Castings Limited": "MAHLEC.NS",
    "Magna International Inc.": "MG.TO",
    "Maharashtra Seamless Limited": "MAHSEAMLES.NS",
    "Mahindra & Mahindra Financial Services Limited": "M&MFIN.NS",
    "Mahindra & Mahindra Limited": "M&M.NS",
    "Mahindra CIE Automotive Limited": "MAHINDCIE.NS",
    "Mahindra EPC Irrigation Limited": "MAHEPC.NS",
    "Mahindra Lifespace Developers Limited": "MAHLIFE.NS",
    "Mahindra Logistics Limited": "MAHLOG.NS",
    "Mahindra Rural Housing Finance Limited": "MHRHFL.NS",
    "Majesco Limited": "MAJESCO.NS",
    "Malapuram Minerals Private Limited": "MALMIN.NS",
    "Malu Paper Mills Limited": "MALUPAPER.NS",
    "Mangalam Cement Limited": "MANGLMCEM.NS",
    "Mangalam Global Enterprise Limited": "MGEL.NS",
    "Manhattan Associates, Inc.": "MANH.NS",
    "Man Industries (India) Limited": "MANINDS.NS",
    "Man Infraconstruction Limited": "MANINFRA.NS",
    "Manappuram Finance Limited": "MANAPPURAM.NS",
    "Manchanda Packers & Allied Services Limited": "MANPACK.NS",
    "Mandhana Industries Limited": "MANIND.NS",
    "Mangalore Chemicals & Fertilizers Limited": "MANGCHEFER.NS",
    "Manjushree Technopak Limited": "MANJUSHREE.NS",
    "Manomay Tex India Limited": "MANOMAY.NS",
    "Manpasand Beverages Limited": "MANPASAND.NS",
    "Mantri Developers Private Limited": "MANTRI.NS",
    "Manugraph India Limited": "MANUGRAPH.NS",
    "MapmyIndia": "MAPMYINDIA.NS",
    "Maral Overseas Limited": "MARALOVER.NS",
    "Marico Limited": "MARICO.NS",
    "Markolines Pavement Technologies Limited": "MARKOLINES.NS",
    "Marriott International, Inc.": "MAR.NS",
    "Marsons Limited": "MARSONS.NS",
    "Martin & Harris Label Closures Limited": "MARTINHAR.NS",
    "Martin Burn Limited": "MARTINBURN.NS",
    "Marvel Agrotech Limited": "MARVEL.NS",
    "Maruti Suzuki India Limited": "MARUTI.NS",
    "Masco Corporation": "MASCO.NS",
    "Masuwn Group": "MASUWN.NS",
    "Master Trust Limited": "MASTERTRST.NS",
    "Mastek Limited": "MASTEK.NS",
    "Matrimony.com Limited": "MATRIMONY.NS",
    "Mattel, Inc.": "MAT.NS",
    "Max Healthcare Institute Limited": "MAXHEALTH.NS",
    "Max Financial Services Limited": "MFSL.NS",
    "Max India Limited": "MAXIND.NS",
    "Max Ventures and Industries Limited": "MAXVIL.NS",
    "MaxVIL": "MAXVIL.NS",
    "Mcleod Russel India Limited": "MCLEODRUSS.NS",
    "MCON": "MCON.NS",
    "Medanta - The Medicity": "MEDANTA.NS",
    "Medico Labs Limited": "MEDICOLABS.NS",
    "Medplus Health Services Limited": "MEDPLUS.NS",
    "Meenakshi Enterprises Limited": "MEENAKSHI.NS",
    "Meghmani Finechem Limited": "MEGHFIN.NS",
    "Meghmani Organics Limited": "MEGH.NS",
    "Mehta Integrated Finance Limited": "MEHTAINTEG.NS",
    "Mehta Securities Limited": "MEHTASEC.NS",
    "Metropolis Healthcare Limited": "METROPOLIS.NS",
    "Metso Outotec": "MOCORP.HE",
    "MG Motor India Private Limited": "MGMI.NS",
    "MGA": "MGA.NS",
    "MIC Electronics Limited": "MICEL.NS",
    "Micromax Informatics Limited": "MMX.NS",
    "Microsoft Corporation": "MSFT.NS",
    "Mid-America Apartment Communities": "MAA.NS",
    "Minda Corporation Limited": "MINDACORP.NS",
    "Minda Industries Limited": "MINDAINDA.NS",
    "Mindtree Limited": "MINDTREE.NS",
    "Minolta India Private Limited": "MINOLTA.NS",
    "Mirza International Limited": "MIRZAINT.NS",
    "Mishtann Foods Limited": "MISHTANN.NS",
    "Mishra Dhatu Nigam Limited": "MIDHANI.NS",
    "Mishra Engineering Enterprises Limited": "MEE.NS",
    "Mittal Life Style Limited": "MITTALIFE.NS",
    "Miyoshi India Limited": "MIYOSHI.NS",
    "MM Forgings Limited": "MMFL.NS",
    "MMTC Limited": "MMTC.NS",
    "Mobileye Global Inc.": "MBLY.NS",
    "Modi Rubber Limited": "MODIRUBBER.NS",
    "Modipon Limited": "MODIPON.NS",
    "Modi's Surya Prakash Limited": "MSPL.NS",
    "Mold-Tek Packaging Limited": "MOLDTKPAC.NS",
    "Moldtek Systems Limited": "MOLDTEKSYS.NS",
    "Moly Mines Limited": "MOLY.AX",
    "Monarch Networth Capital Limited": "MONARCH.NS",
    "Monnet Ispat & Energy Limited": "MONNET.NS",
    "Monotype Imaging Holdings, Inc.": "TYPE.NS",
    "Motherson Sumi Systems Limited": "MOTHERSUMI.NS",
    "Motor & General Finance Limited": "MOTOGENFIN.NS",
    "Motor Industries Company of India Limited": "MICO.NS",
    "Mount Row Capital Limited": "MRC.NS",
    "MphasiS Limited": "MPHASIS.NS",
    "MRF Limited": "MRF.NS",
    "MRPL Limited": "MRPL.NS",
    "MSR India Limited": "MSRI.NS",
    "MTAR Technologies Limited": "MTARTECH.NS",
    "Mueller Industries, Inc.": "MLI.NS",
    "Mukand Engineers Limited": "MUKANDENGG.NS",
    "Mukand Limited": "MUKAND.NS",
    "Mukta Arts Limited": "MUKTAARTS.NS",
    "Multi Commodity Exchange of India Limited": "MCX.NS",
    "Mumbai Debt Recovery Company Limited": "MDRC.NS",
    "Muthoot Capital Services Limited": "MUTHOOTCAP.NS",
    "Muthoot Finance Limited": "MUTHOOTFIN.NS",
    "Mysore Petro Chemicals Limited": "MYPETROC.NS",
    "NACL Industries Limited": "NACLIND.NS",
    "Nagarjuna Construction Company Limited": "NCC.NS",
    "Nagarjuna Fertilizers and Chemicals Limited": "NAGAFERT.NS",
    "Naked Wines plc": "WINE.L",
    "Nandan Denim Limited": "NDL.NS",
    "Nandan Power Total Solutions Private Limited": "NANDAN.NS",
    "Nandini Piramal Enterprises Private Limited": "NPET.NS",
    "Narayana Hrudayalaya Limited": "NH.NS",
    "Narmada Gelatines Limited": "NARMADA.NS",
    "National Aluminium Company Limited": "NATIONALUM.NS",
    "National Buildings Construction Corporation Limited": "NBCC.NS",
    "National High Speed Rail Corporation Limited": "NHSRCL.NS",
    "National Hydroelectric Power Corporation Limited": "NHPC.NS",
    "National Infrastructure Pipeline": "NIP.NS",
    "National Mineral Development Corporation Limited": "NMDC.NS",
    "National Peroxide Limited": "NATIONALUM.NS",
    "National Steel and Agro Industries Limited": "NSAIL.NS",
    "Natco Pharma Limited": "NATCOPHARM.NS",
    "Nath Bio-Genes (India) Limited": "NATHBIOG.NS",
    "Navin Fluorine International Limited": "NAVINFLUOR.NS",
    "Navkar Urbanstructure Limited": "NAVKAR.NS",
    "Navketan Merchants Private Limited": "NAVKETAN.NS",
    "NBCC (India) Limited": "NBCC.NS",
    "NCC Limited": "NCC.NS",
    "Nesco Limited": "NESCO.NS",
    "Nestle India Limited": "NESTLEIND.NS",
    "Netherland Company Limited": "NETHERLAND.NS",
    "Network18 Media & Investments Limited": "NETWORK18.NS",
    "Neuland Laboratories Limited": "NEULANDLAB.NS",
    "New Delhi Television Limited": "NDTV.NS",
    "Newgen Software Technologies Limited": "NEWGEN.NS",
    "Next Education India Private Limited": "NEXTEDU.NS",
    "Nexus Select Trust": "NEXUS.NS",
    "Nila Spaces Limited": "NILASPACES.NS",
    "Nila Infrastructures Limited": "NILAINFRA.NS",
    "Nilesh Laboratories Limited": "NILESHLAB.NS",
    "Nirlon Limited": "NIRLON.NS",
    "Nissan Motor Co., Ltd.": "7201.T",
    "Nitesh Estates Limited": "NITESHEAT.NS",
    "Nitin Fire Protection Industries Limited": "NITINFPRO.NS",
    "Nitin Gandhi": "NITIN.NS",
    "Nitin Spinners Limited": "NITINSPIN.NS",
    "Niva Bupa Health Insurance Company Limited": "NIVABUPA.NS",
    "NMDC Steel Limited": "NMDCSTEEL.NS",
    "NOCIL Limited": "NOCIL.NS",
    "Noida Toll Bridge Company Limited": "NOIDATOLL.NS",
    "Norbord Inc.": "OSB.TO",
    "Norflex": "NORFLEX.NS",
    "Normet Oy": "NORMET.HE",
    "North Eastern Carrying Corporation Limited": "NECC.NS",
    "Norton Rose Fulbright": "NRF.NS",
    "Nova Agritech Limited": "NOVAAGRI.NS",
    "Nova Gold Resources Inc.": "NG.TO",
    "Nova Iron Limited": "NVA.AX",
    "Novartis AG": "NOVN.SW",
    "Novavax, Inc.": "NVAX.NS",
    "NRF": "NRF.NS",
    "NTPC Limited": "NTPC.NS",
    "NU Hospitals Limited": "NUHOSP.NS",
    "Nucleus Software Exports Limited": "NUCLEUS.NS",
    "Nuvoco Vistas Corp Limited": "NUVOCO.NS",
    "Nuvama Wealth Management Limited": "NUVAMA.NS",
    "O. N. G. C. Limited": "ONGC.NS",
    "Oasis Tradelink Limited": "OASIS.NS",
    "Oberoi Realty Limited": "OBEROIRLTY.NS",
    "OCL India Limited": "OCL.NS",
    "Odisha Mining Corporation Limited": "OMCL.NS",
    "Oil and Natural Gas Corporation Limited": "ONGC.NS",
    "Oil Country Tubular Limited": "OILCOUNTUB.NS",
    "Oil India Limited": "OIL.NS",
    "Olectra Greentech Limited": "OLECTRA.NS",
    "Olikara Holdings Private Limited": "OLIKARA.NS",
    "Ollie": "OLLIE.NS",
    "Omax Autos Limited": "OMAXAUTO.NS",
    "Omaxe Limited": "OMAXE.NS",
    "Omega Micro Systems & Solutions Limited": "OMEGA.NS",
    "Omkar Speciality Chemicals Limited": "OMKARCHEM.NS",
    "ONGC Videsh Limited": "OVL.NS",
    "Oonchu": "OONCHU.NS",
    "Optiemus Infracom Limited": "OPTIEMUS.NS",
    "Opto Circuits (India) Limited": "OPTOCIRCUI.NS",
    "Oracle Financial Services Software Limited": "OFSS.NS",
    "Orient Electric Limited": "ORIENTELEC.NS",
    "Orient Green Power Company Limited": "GREENPOWER.NS",
    "Orient Paper & Industries Limited": "ORIENTPPR.NS",
    "Orient Technologies Limited": "ORIENTTECH.NS",
    "Orient Trading Company Limited": "ORIENTTRADE.NS",
    "Orient Cement Limited": "ORIENTCEM.NS",
    "Oriental Carbon & Chemicals Limited": "OCCL.NS",
    "Oriental Hotels Limited": "ORIENTHOT.NS",
    "Oriental Trimble Limited": "OTL.NS",
    "Orissa Minerals Development Company Limited": "OMDC.NS",
    "Orrick": "ORRICK.NS",
    "Osho Industries Limited": "OSHO.NS",
    "Oswal Agro Mills Limited": "OSWALAGRO.NS",
    "Otsuka Chemical Holdings Co., Ltd.": "4768.T",
    "Otsuka Corporation": "OTSUKA.T",
    "Otsuka Kagu Ltd.": "8179.T",
    "Oulu": "OULU.FI",
    "Overstone Group": "OVERS.NS",
    "Ozone India Limited": "OZONE.NS",
    "P&G Chemicals": "PGCHEM.NS",
    "P&G Health Limited": "PGHL.NS",
    "P.I. Industries Limited": "PIIND.NS",
    "PNC Infratech Limited": "PNCINFRA.NS",
    "Praj Industries Limited": "PRAJIND.NS",
    "Prakash Industries Limited": "PRAKASH.NS",
    "Prakash Steelage Limited": "PRAKASHSTL.NS",
    "Praman Industries Limited": "PRAMAN.NS",
    "Prataap Snacks Limited": "PRATAAP.NS",
    "Precision Electronics Limited": "PRECAM.NS",
    "Precot Limited": "PRECOT.NS",
    "Premier Energies Limited": "PREMIERENE.NS",
    "Premier Explosives Limited": "PEX.NS",
    "Premier Polyfilm Limited": "PREMIERPOL.NS",
    "Premier Limited": "PREMIER.NS",
    "Pressure Sensitive Systems (India) Limited": "PRESSMN.NS",
    "Prestige Estates Projects Limited": "PRESTIGE.NS",
    "Prism Johnson Limited": "PRSMJOHNSON.NS",
    "Pritika Auto Industries Limited": "PRITIKAAUTO.NS",
    "PNC Infratech Limited": "PNCINFRA.NS",
    "Procter & Gamble Hygiene and Health Care Limited": "PGHH.NS",
    "Profin Capital Services Limited": "PROFIN.NS",
    "Prozone Intu Properties Limited": "PROZONINTU.NS",
    "PSP Projects Limited": "PSPPROJECTS.NS",
    "PTC India Financial Services Limited": "PTCIFS.NS",
    "PTC Industries Limited": "PTCIL.NS",
    "PTC India Limited": "PTC.NS",
    "Pudumjee Paper Products Limited": "PUDUMJEE.NS",
    "Pulsar International Limited": "PULSAR.NS",
    "Punjab & Sind Bank": "PSB.NS",
    "Punjab Alkalies & Chemicals Limited": "PANKAJPOLY.NS",
    "Punjab Chemicals and Crop Protection Limited": "PCCL.NS",
    "Punjab National Bank": "PNB.NS",
    "Puravankara Limited": "PURVA.NS",
    "Pure Indiamart Limited": "INDIAMART.NS",
    "PVR INOX Limited": "PVRINOX.NS",
    "PVP Ventures Limited": "PVP.NS",
    "Pyramid Technoplast Private Limited": "PYRAMID.NS",
    "QMS Medical Allied Services Limited": "QMS.NS",
    "Quess Corp Limited": "QUESS.NS",
    "Quick Heal Technologies Limited": "QUICKHEAL.NS",
    "R R Kabel Limited": "RRKABEL.NS",
    "R.S. Software (India) Limited": "RSSOFTWARE.NS",
    "R1 RCM Inc.": "RCM.NS",
    "Rachana Infrastructure Limited": "RACHANA.NS",
    "Racold": "RACOLD.NS",
    "Radico Khaitan Limited": "RADICO.NS",
    "Radius Developers Limited": "RADIUS.NS",
    "Rage Communications Limited": "RAGE.NS",
    "Rahul Sarees Private Limited": "RAHULSAREE.NS",
    "Rail Vikas Nigam Limited": "RVNL.NS",
    "Rainbow Children's Medicare Limited": "RAINBOW.NS",
    "Rainbow Papers Limited": "RAINBOWPAP.NS",
    "Rain Industries Limited": "RAIN.NS",
    "Rallis India Limited": "RALLIS.NS",
    "Ram Ratna Wires Limited": "RAMRAT.NS",
    "Rama Steel Tubes Limited": "RAMASTEEL.NS",
    "Ramco Cements Limited": "RAMCOCEM.NS",
    "Ramco Systems Limited": "RAMCOSYS.NS",
    "Ramkrishna Forgings Limited": "RKFORGE.NS",
    "Ramsons Projects Limited": "RAMSONS.NS",
    "Rane (Madras) Limited": "RANEHOLDIN.NS",
    "Rane Brake Lining Limited": "RANEENGINE.NS",
    "Rane Holdings Limited": "RANEHOLDIN.NS",
    "Rangoli Tradecomm Limited": "RANGOLI.NS",
    "Rapiddomains": "RAPIDDOM.NS",
    "Rashi Peripherals Limited": "RASHI.NS",
    "RattanIndia Enterprises Limited": "RTNINDIA.NS",
    "RattanIndia Power Limited": "RTNPOWER.NS",
    "Ravindra Energy Limited": "RAVINDRA.NS",
    "Raymon Engineering Works Limited": "RAYMON.NS",
    "RBM Infracon Limited": "RBMINFRA.NS",
    "RCF Limited": "RCF.NS",
    "RDB Realty & Infrastructure Limited": "RDBREALTY.NS",
    "Readymade Steel India Limited": "RSTLTD.NS",
    "Realty Income Corporation": "O.NS",
    "Redington Limited": "REDINGTON.NS",
    "Refex Industries Limited": "REFEX.NS",
    "Refex Refrigerants Limited": "REFEXREF.NS",
    "Regal Entertainment Group": "RGC.NS",
    "Regency Ceramics Limited": "REGENCERAM.NS",
    "Reliance Home Finance Limited": "RHFL.NS",
    "Reliance Industrial Infrastructure Limited": "RIIL.NS",
    "Reliance Infrastructure Limited": "RELINFRA.NS",
    "Reliance Power Limited": "RPOWER.NS",
    "Reliance Retail Ventures Limited": "RRVL.NS",
    "Reliance": "RELIANCE.NS",
    "Religare Enterprises Limited": "RELIGARE.NS",
    "Religare Finvest Limited": "RELIGFINV.NS",
    "Relish Foods Limited": "RELISH.NS",
    "Remsons Industries Limited": "REMSONSIND.NS",
    "Renishaw plc": "RSW.L",
    "Renuka Sugars Limited": "RENUKASUG.NS",
    "Repco Home Finance Limited": "REPCOHOME.NS",
    "Resgen Group": "RESGEN.NS",
    "Restaurant Brands International Inc.": "QSR.TO",
    "Revelis India Limited": "REVELIS.NS",
    "Revathi Equipment Limited": "REVATHIEQ.NS",
    "Revolution Medicines, Inc.": "RVMD.NS",
    "RFCL Limited": "RFCL.NS",
    "Rico Auto Industries Limited": "RICOAUTO.NS",
    "Ride On Toys Private Limited": "RIDEON.NS",
    "Rihai Tubes Private Limited": "RIHAI.NS",
    "RITES Limited": "RITES.NS",
    "Rivaan Foodworks Private Limited": "RIVAA.NS",
    "Ruchi Soya Industries Limited": "RPL.NS",
    "Rudrabhishek Enterprises Limited": "REPL.NS",
    "Rudra Global Infra Products Limited": "RUDRAGLOB.NS",
    "Rudramsh": "RUDRAMSH.NS",
    "Rupa & Company Limited": "RUPA.NS",
    "Rupee Power": "RUPEE.NS",
    "Rushi Care Limited": "RUSHI.NS",
    "Ruttonsha International Rectifier Limited": "RUTTONSHA.NS",
    "Ruvati": "RUVATI.NS",
    "RVNL": "RVNL.NS",
    "S&T Corporation": "STCO.T",
    "S H Kelkar and Company Limited": "KELAR.NS",
    "S.K.M. Animal Feeds and Foods Limited": "SKMEGG.NS",
    "S.P. Apparels Limited": "SPAPP.NS",
    "S.S. Organics Limited": "SSORGANIC.NS",
    "Sacheerome Limited": "SACHEEROME.NS",
    "Sadhana Nitro Chem Limited": "SADHNANIQ.NS",
    "Safari Industries (India) Limited": "SAFARI.NS",
    "Sagar Cements Limited": "SAGCEMENT.NS",
    "Sahara Housingfina Corporation Limited": "SAHARA.NS",
    "Sahyadri Agencies Limited": "SAHYADRI.NS",
    "Sai Silk (India) Limited": "SAISILK.NS",
    "Sakal Papers Private Limited": "SAKAL.NS",
    "Salasar Techno Engineering Limited": "SALASAR.NS",
    "Sales India Limited": "SALESIND.NS",
    "Sallas Hospitality Private Limited": "SALLAS.NS",
    "Sallas Hospitality": "SALLAS.NS",
    "Salona Cotspin Limited": "SALONACOT.NS",
    "Sam Industries Limited": "SAMIND.NS",
    "Sambhaav Media Limited": "SAMBHAAV.NS",
    "Sambhu Dairy Products Limited": "SAMBHU.NS",
    "Samhi Hotels Limited": "SAMHI.NS",
    "Sampann Agriculture Limited": "SAMPANN.NS",
    "Samsung India Electronics Private Limited": "SIEPL.NS",
    "Sandhar Technologies Limited": "SANDHAR.NS",
    "Sandvik Asia Private Limited": "SANDVIK.NS",
    "Sangam (India) Limited": "SANGAMIND.NS",
    "Sanghvi Movers Limited": "SANGHVIMOV.NS",
    "Sanjivani Non-Ferrous Trading Private Limited": "SANJIVANI.NS",
    "Sankhya Infotech Limited": "SANKHYA.NS",
    "Sansera Engineering Limited": "SANSERA.NS",
    "Santosh Fine-Fab Limited": "SANTOFINF.NS",
    "Saregama India Limited": "SAREGAMA.NS",
    "Sarla Performance Fibers Limited": "SARLAPOLY.NS",
    "Sarup Industries Limited": "SARUPIND.NS",
    "Sasken Technologies Limited": "SASKEN.NS",
    "Sathlokhar Synergys E&C Global Limited": "SATHLOKHAR.NS",
    "Satin Creditcare Network Limited": "SATIN.NS",
    "Saurashtra Cement Limited": "SAURASHTRC.NS",
    "Savera Hotels Limited": "SAVERA.NS",
    "Savera Industries Limited": "SAVERAINDS.NS",
    "Savita Oil Technologies Limited": "SAVITA.NS",
    "Schaeffler India Limited": "SCHAEFFLER.NS",
    "Schneider Electric Infrastructure Limited": "SCHNEIDER.NS",
    "Scoop Industries Private Limited": "SCOOP.NS",
    "Scott Technology Limited": "SCT.NZ",
    "SEAMEC Limited": "SEAMECLTD.NS",
    "Sealand Securities Ltd.": "SEALAND.NS",
    "Sebastian": "SEBASTIAN.NS",
    "Securekloud Technologies Limited": "SECUREKLOUD.NS",
    "Sejal Glass Limited": "SEJALLTD.NS",
    "Sejha": "SEJHA.NS",
    "Selan Exploration Technology Limited": "SELAN.NS",
    "Sellwin Traders Limited": "SELLWIN.NS",
    "Senco Gold Limited": "SENCO.NS",
    "Sennheiser": "SENNHEISER.NS",
    "Sensibull": "SENSIBULL.NS",
    "Senti Biosciences, Inc.": "SNTI.NS",
    "Senyas": "SENYAS.NS",
    "Serein": "SEREIN.NS",
    "Seshasayee Paper and Boards Limited": "SESHAPAPER.NS",
    "Sethia Oils Limited": "SETHIAOIL.NS",
    "Sethia Solvents & Derivatives Limited": "SETHIA.NS",
    "Seya Industries Limited": "SEYAIND.NS",
    "Shaily Engineering Plastics Limited": "SHAILY.NS",
    "Shalby Limited": "SHALBY.NS",
    "Shalimar Paints Limited": "SHALIMAR.NS",
    "Shalimar Productions Limited": "SHALPROD.NS",
    "Shamken Multifab Limited": "SHAMKEN.NS",
    "Shankara Building Products Limited": "SHANKARA.NS",
    "Shanthi Gears Limited": "SHANTIGEAR.NS",
    "Shapoorji Pallonji Engineering & Construction Private Limited": "SPENC.NS",
    "Sharda Cropchem Limited": "SHARDACROP.NS",
    "Shardul Amarchand Mangaldas & Co": "SAMCO.NS",
    "Sharp India Private Limited": "SHARP.NS",
    "Shavo Technologies Limited": "SHAVO.NS",
    "Shaw Wallace": "SHAWALLACE.NS",
    "Sheela Foam Limited": "SHEELAFOAM.NS",
    "Shekhawati Polyspin Limited": "SHEKHAWATI.NS",
    "Shekhawati Textile Mills Limited": "SHKHTXTML.NS",
    "Shilpa Medicare Limited": "SHILPAMED.NS",
    "Shine Fashions Limited": "SHINEFNS.NS",
    "Shinto Holdings Inc.": "6337.T",
    "Shiprocket": "SHIPROCKET.NS",
    "Shiraishi": "SHIRAISHI.NS",
    "Shirpur Gold Refinery Limited": "SHIRPURGOLD.NS",
    "Shivam Autotech Limited": "SHIVAMAUTO.NS",
    "Shivani Locks Private Limited": "SHIVANI.NS",
    "Shree Cement Limited": "SHREECEM.NS",
    "Shree Digvijay Cement Company Limited": "SHRDIGVICEM.NS",
    "Shree Global Tradefin Limited": "SHGLOBAL.NS",
    "Shree Hanuman Cotton Limited": "SHREECOTTON.NS",
    "Shree Karthik Papers Limited": "SHREEKARTHK.NS",
    "Shree Krishna Paper Mills & Industries Limited": "SHREEMILLS.NS",
    "Shree Pushkar Raj Industries Limited": "SHREEPUSHK.NS",
    "Shree Ram Urban Infrastructure Limited": "SHREERAMAUR.NS",
    "Shree Rajasthan Syntex Limited": "SHREERJSYNTX.NS",
    "Shree Rama Newsprint Limited": "RAMANEWS.NS",
    "Shree Renuka Sugars Limited": "RENUKASUG.NS",
    "Shree Sekhri Mills Limited": "SHREESEKHRI.NS",
    "Shree Vasu Logistics Limited": "SVLL.NS",
    "Shreeji Shipping Limited": "SHREEJISHIP.NS",
    "Shriram Asset Management Company Limited": "SHRIRAMAMC.NS",
    "Shriram Finance Limited": "SRAM.NS",
    "Shriram Properties Limited": "SHRIRAMPRO.NS",
    "Shriram Transport Finance Company Limited": "SRTRANSFIN.NS",
    "Shubhlaxmi Finance Limited": "SHUBHLAXMI.NS",
    "Shyam Century Ferrous Limited": "SHYAMCENT.NS",
    "Shyam Metalics and Energy Limited": "SHYAMMETL.NS",
    "Shyam Telelink Limited": "SHYAMTEL.NS",
    "Sicom Limited": "SICOM.NS",
    "Siemens Energy AG": "ENR.DE",
    "Siemens Gamesa Renewable Energy S.A.": "SGRE.MC",
    "Siemens Healthineers AG": "SHL.DE",
    "Siemens Limited": "SIEMENS.NS",
    "Signet Industries Limited": "SIGNET.NS",
    "Sika Interplant Systems Limited": "SIKA.NS",
    "Sikko Industries Limited": "SIKKO.NS",
    "Sikri": "SIKRI.NS",
    "Silgo Retail Limited": "SILGO.NS",
    "Silicon Valley Infotech Private Limited": "SVIL.NS",
    "Sillouette": "SILLOUETTE.NS",
    "Silver Touch Technologies Limited": "SILVERTUC.NS",
    "Silverline Technologies Limited": "SILVERTNL.NS",
    "Simbhaoli Sugars Limited": "SIMBHALS.NS",
    "Simmonds Marshall Machinery Limited": "SIMMMACH.NS",
    "Simon India Limited": "SIMON.NS",
    "Simplex Castings Limited": "SIMPLEX.NS",
    "Simplex Infrastructures Limited": "SIMPLEXINF.NS",
    "Simplex Mills Company Limited": "SIMPLEXMW.NS",
    "Simplex Papers Limited": "SIMPLEXPAP.NS",
    "Simpson & Company Limited": "SIMPSON.NS",
    "Sindhu Trade Links Limited": "SINDHUTRAD.NS",
    "Singapore Airlines Limited": "C6L.SI",
    "Singer India Limited": "SINGER.NS",
    "Sintercom India Limited": "SINTERCOM.NS",
    "Sirca Paints India Limited": "SIRCAPNT.NS",
    "Siri": "SIRI.NS",
    "Sirpur Paper Mills Limited": "SIRPURPAP.NS",
    "Sita Enterprises & Holding Company Limited": "SITAEHCL.NS",
    "Sita World Travel": "SITAW.NS",
    "SITAR": "SITAR.NS",
    "SJVN Limited": "SJVN.NS",
    "SKF India Limited": "SKFINDIA.NS",
    "Skipper Limited": "SKIPPER.NS",
    "Sky Gold & Diamonds Limited": "SKYGOLD.NS",
    "Sky Industries Limited": "SKYIND.NS",
    "Skyroot Aerospace": "SKYROOT.NS",
    "Slayden": "SLAYDEN.NS",
    "SMC Global Securities Limited": "SMCGLOBAL.NS",
    "SMS Lifesciences India Limited": "SMSLIFE.NS",
    "SMT Continental Hotels Limited": "SMTCH.NS",
    "Snowflake Inc.": "SNOW.NS",
    "Sobha Limited": "SOBHA.NS",
    "Sodexo": "SW.PA",
    "Sohum Fertilisers & Chemicals Limited": "SOHUM.NS",
    "Solara Active Pharma Sciences Limited": "SOLARA.NS",
    "Solar Industries India Limited": "SOLARINDS.NS",
    "Solaris Resources Inc.": "SLS.TO",
    "Soma Textiles & Industries Limited": "SOMATEXT.NS",
    "Somany Ceramics Limited": "SOMANYCERA.NS",
    "Sona BLW Precision Forgings Limited": "SONACOMS.NS",
    "Sonam Limited": "SONAM.NS",
    "Sonata Software Limited": "SONATSOFTW.NS",
    "Sona Valliappa Industries Limited": "SONAVAL.NS",
    "Sonata": "SONATA.NS",
    "Soni Soya Products Limited": "SONISOYA.NS",
    "Sony Pictures Networks India Private Limited": "SPNIPL.NS",
    "Soril Infra Resources Limited": "SORIL.NS",
    "Sotefin SA": "SOTEFIN.PA",
    "Southern Ferro Limited": "SOUTHERNFE.NS",
    "Southern Magnesium & Chemicals Limited": "SMC.NS",
    "Southern Sales & Services Limited": "SOUTHERNSL.NS",
    "SouthWest Michigan First": "SWMICH.NS",
    "SP Apparels Limited": "SPAPP.NS",
    "SPIC Limited": "SPIC.NS",
    "SPML Infra Limited": "SPMLINFRA.NS",
    "Sports & Recreation Limited": "SPRTREC.NS",
    "SPS International Limited": "SPSINTL.NS",
    "Sree Jayalakshmi Autospin Limited": "SJAL.NS",
    "Sree Rama Sugars Limited": "SREERAMA.NS",
    "Sree Rayalaseema Hi-Strength Hypo Limited": "SRHHYPOLTD.NS",
    "Sreeleathers Limited": "SREELEATHR.NS",
    "Sreenidhi": "SREENIDHI.NS",
    "Srei Infrastructure Finance Limited": "SREINFRA.NS",
    "Srichakra Industries Limited": "SRICHK.NS",
    "SRM Contractors Limited": "SRMC.NS",
    "SS Music": "SSMU.NS",
    "Stadmed Private Limited": "STADMED.NS",
    "Standard Capital Markets Limited": "STANCAP.NS",
    "Standard Chartered PLC": "STAN.L",
    "Standard Fireworks Private Limited": "STANDFIRE.NS",
    "Stanpacks (India) Limited": "STANPACK.NS",
    "Star Health and Allied Insurance Company Limited": "STARHEALTH.NS",
    "Star Paper Mills Limited": "STAR.NS",
    "Starlineps": "STARLINEPS.NS",
    "Stel Holdings Limited": "STEL.NS",
    "Stellar Capital Services Limited": "STELLAR.NS",
    "Sterlite Technologies Limited": "STLTECH.NS",
    "Stewarts": "STEWARTS.NS",
    "Stovekraft Limited": "STOVEKRAFT.NS",
    "Strides Pharma Science Limited": "STAR.NS",
    "Strix Group Limited": "KUIK.L",
    "Stromberg": "STROMBERG.NS",
    "Strides": "STAR.NS",
    "Styrenix Performance Materials Limited": "STYRENIX.NS",
    "Subros Limited": "SUBROS.NS",
    "Subros Limited": "SUBROS.NS",
    "Sudarshan Chemical Industries Limited": "SUDARSCHEM.NS",
    "Suditi Industries Limited": "SUDITI.NS",
    "Sufal Foods Private Limited": "SUFAL.NS",
    "Sula Vineyards Limited": "SULA.NS",
    "Sumeet Industries Limited": "SUMEETINDS.NS",
    "Sundaram Clayton Limited": "SUNCLAY.NS",
    "Sundaram Finance Holdings Limited": "SUNDARMHLD.NS",
    "Sundaram Finance Limited": "SUNDARMFIN.NS",
    "Sundaram Multi Pap Limited": "SMP.NS",
    "Sundaram-Clayton Limited": "SUNCLAY.NS",
    "Sunflag Iron & Steel Company Limited": "SUNFLAG.NS",
    "Sunil Healthcare Limited": "SUNILH.NS",
    "Sunil Hitech Engineers Limited": "SUNILHitech.NS",
    "Sun Pharma Advanced Research Company Limited": "SPARC.NS",
    "Sun Pharmaceutical Industries Limited": "SUNPHARMA.NS",
    "Sundial Growers Inc.": "SNDL.NS",
    "Sunflag Iron": "SUNFLAG.NS",
    "Sunrise Capital India Private Limited": "SUNRISE.NS",
    "Sunrise": "SUNRISE.NS",
    "Sunteck Realty Limited": "SUNTECK.NS",
    "Super Sales India Limited": "SSIL.NS",
    "Super Spinning Mills Limited": "SUPERSPIN.NS",
    "Suprajit Engineering Limited": "SUPRAJIT.NS",
    "Supreme Industries Limited": "SUPREMEIND.NS",
    "Supreme": "SUPREME.NS",
    "Supreme Infrastructure India Limited": "SUPREMEINF.NS",
    "Suryalakshmi Cotton Mills Limited": "SURYALAXMI.NS",
    "Suryalaxmi": "SURYALAXMI.NS",
    "Suryoday Small Finance Bank Limited": "SURYODAY.NS",
    "Sutlej Textiles and Industries Limited": "SUTLEJTEX.NS",
    "Suzlon Energy Limited": "SUZLON.NS",
    "Swan Energy Limited": "SWANENERGY.NS",
    "Swara Digital": "SWARA.NS",
    "Swastik Pipe Limited": "SWASTIK.NS",
    "Swathi": "SWATHI.NS",
    "Swiggy": "SWIGGY.NS",
    "Syngene International Limited": "SYNGENE.NS",
    "Synoptics": "SYNOPTICS.NS",
    "Syrma SGS Technology Limited": "SYRMA.NS",
    "Systematix Corporate Services Limited": "SYSTEMATIX.NS",
    "T N Newsprint & Papers Limited": "TNNEWS.NS",
    "T. Stanes & Company Limited": "STANES.NS",
    "T.M.C. Limited": "TMC.NS",
    "Tamilnad Mercantile Bank Limited": "TMB.NS",
    "Tamilnadu Petroproducts Limited": "TNPETRO.NS",
    "Taneja Aerospace & Aviation Limited": "TANEJAERO.NS",
    "Tantia Constructions Limited": "TANTIACONS.NS",
    "Tara": "TARA.NS",
    "Tara Jewels Limited": "TARAJEWELS.NS",
    "Tarc Limited": "TARC.NS",
    "Target": "TGT.NS",
    "Tata Advanced Systems Limited": "TASL.NS",
    "Tata AIA Life Insurance Company Limited": "TATAIANS.NS",
    "Tata Capital Housing Finance Limited": "TCHF.NS",
    "Tata Capital Limited": "TATACAP.NS",
    "Tata Chemicals Limited": "TATACHEM.NS",
    "Tata Communications Limited": "TATACOMM.NS",
    "Tata Consultancy Services Limited": "TCS.NS",
    "Tata Consumer Products Limited": "TATACONSUM.NS",
    "Tata Elxsi Limited": "TATAELXSI.NS",
    "Tata Housing Development Company Limited": "TATAHOUSING.NS",
    "Tata Investment Corporation Limited": "TATAINVEST.NS",
    "Tata Metaliks Limited": "TATAMETALI.NS",
    "Tata Motors Limited": "TATAMOTORS.NS",
    "Tata Power Company Limited": "TATAPOWER.NS",
    "Tata Technologies Limited": "TATATECH.NS",
    "Tata Teleservices (Maharashtra) Limited": "TTML.NS",
    "TCI Express Limited": "TCIEXP.NS",
    "TCNS Clothing Co. Limited": "TCNSBRANDS.NS",
    "TD Power Systems Limited": "TDPOWERSYS.NS",
    "Teamo": "TEAMO.NS",
    "TeamLease Services Limited": "TEAMLEASE.NS",
    "Tech Mahindra Limited": "TECHM.NS",
    "Technoclean Hygienics Limited": "TECHCLEAN.NS",
    "Technofab Engineering Limited": "TECHNOFAB.NS",
    "Tecnotree Corporation": "TEM1V.HE",
    "Teerth Gopicon Limited": "TEERTH.NS",
    "Tejas Networks Limited": "TEJASNET.NS",
    "Teknikon": "TEKNIKON.NS",
    "Teleperformance SE": "TEP.PA",
    "Tembo Global Industries Limited": "TEMBO.NS",
    "Tembo": "TEMBO.NS",
    "Tera Software Limited": "TERASOFT.NS",
    "Tesla, Inc.": "TSLA.NS",
    "Texmaco Infra Engineering Limited": "TEXINFRA.NS",
    "Texmaco Rail & Engineering Limited": "TEXRAIL.NS",
    "Texmo Pipes and Products Limited": "TEXMOPIPES.NS",
    "Thacker and Company Limited": "THACKER.NS",
    "Thangamayil Jewellery Limited": "THANGAMAYL.NS",
    "Thapar": "THAPAR.NS",
    "The Anup Engineering Limited": "ANUP.NS",
    "The Bombay Dyeing and Manufacturing Company Limited": "BOMDYEING.NS",
    "The Federal Bank Limited": "FEDERALBNK.NS",
    "The Great Eastern Shipping Company Limited": "GESHIP.NS",
    "The Indian Hotels Company Limited": "INDHOTEL.NS",
    "The Indian Iron And Steel Company Limited": "TISCO.NS",
    "The Jamuna Banks Limited": "JAMUNABANK.NS",
    "The Karnataka Bank Limited": "KTKBANK.NS",
    "The Kerala Minerals and Metals Limited": "KMM.NS",
    "The Kerala State Industrial Development Corporation Limited": "KSIDC.NS",
    "The New India Assurance Company Limited": "NIACL.NS",
    "The Phoenix Mills Limited": "PHOENIXLTD.NS",
    "The South Indian Bank Limited": "SOUTHBANK.NS",
    "The Times Group": "TIMESGROUP.NS",
    "The Ugar Sugar Works Limited": "UGARSUGAR.NS",
    "The United India Insurance Company Limited": "UIIC.NS",
    "The Western India Plywood Limited": "WESTIPLY.NS",
    "Thermodyne Boilers": "THERMODYNE.NS",
    "Thirumalai Chemicals Limited": "TIRUMALCHM.NS",
    "Thomas Cook (India) Limited": "THOMASCOOK.NS",
    "Thomas Scott India Limited": "THOMASSCOT.NS",
    "Thor Industries, Inc.": "THO.NS",
    "Three M Paper Boards Limited": "3MPAPER.NS",
    "Threpsi": "THREPSI.NS",
    "Thryv Holdings, Inc.": "THRY.NS",
    "Thyrocare Technologies Limited": "THYROCARE.NS",
    "Tide Water Oil Company (India) Limited": "TIDEWATER.NS",
    "Tiffin Food & Beverages Private Limited": "TIFFIN.NS",
    "TIL Limited": "TIL.NS",
    "Tilaknagar Industries Limited": "TI.NS",
    "Timex Group India Limited": "TIMEX.NS",
    "Timken India Limited": "TIMKEN.NS",
    "Tinplate Company of India Limited": "TINPLATE.NS",
    "Titan Company Limited": "TITAN.NS",
    "Titan Securities Limited": "TITANSEC.NS",
    "TJSB Sahakari Bank Limited": "TJSB.NS",
    "TMB Limited": "TMB.NS",
    "TML": "TML.NS",
    "TNPetro": "TNPETRO.NS",
    "Tocklai Tea Research Institute": "TOCKLAI.NS",
    "Toddle": "TODDLE.NS",
    "Tokai Carbon Co., Ltd.": "5301.T",
    "Tokyu Construction Co., Ltd.": "1799.T",
    "Tolani Shipping Company Limited": "TOLANI.NS",
    "Toll Brothers, Inc.": "TOL.NS",
    "Tona": "TONA.NS",
    "Tongwei Co., Ltd.": "600438.SS",
    "Toobler": "TOOBLER.NS",
    "Toray Industries, Inc.": "3402.T",
    "Tornier N.V.": "TRNR.AS",
    "Torrent Pharmaceuticals Limited": "TORNTPOWER.NS",
    "Torrent Power Limited": "TORNTPOWER.NS",
    "Total SE": "TTE.PA",
    "Total Transport Corporation of India Limited": "TOTAL.NS",
    "Tourism Finance Corporation of India Limited": "TFCI.NS",
    "Toyoda Gosei Co., Ltd.": "7230.T",
    "Toyotsu": "TOYOTSU.T",
    "Tracxn": "TRACXN.NS",
    "Tractor Forge Private Limited": "TRACTORF.NS",
    "TradeIndia": "TRADEINDIA.NS",
    "Tractor": "TRACTOR.NS",
    "Trans India Holidays Limited": "TIHOLIDAYS.NS",
    "Trans-Himalayan Cold Chain Limited": "THCCL.NS",
    "Transchem Limited": "TRANSCHEM.NS",
    "Transcon Developers Limited": "TRANSCON.NS",
    "Transcorp International Limited": "TRANSINTL.NS",
    "Transpek Industry Limited": "TRANSPEK.NS",
    "Transport Corporation of India Limited": "TCI.NS",
    "Transrail Lighting Limited": "TRANSRALI.NS",
    "Transwind": "TRANSWIND.NS",
    "Travel Food Services Private Limited": "TFSPL.NS",
    "Travel Corporation of India Limited": "TCIL.NS",
    "Travel Food Services": "TFSPL.NS",
    "Travels and Rentals Private Limited": "TRAVELS.NS",
    "Trecon": "TRECON.NS",
    "Tree House Education & Accessories Limited": "TREEHOUSE.NS",
    "Trek": "TREK.NS",
    "Trek": "TREK.NS",
    "Trend": "TREND.NS",
    "Trent Limited": "TRENT.NS",
    "Trial": "TRIAL.NS",
    "Tribhovandas Bhimji Zaveri Limited": "TBZ.NS",
    "Trident Limited": "TRIDENT.NS",
    "Triloki Industries Private Limited": "TRILOKI.NS",
    "Trilokya": "TRILOKYA.NS",
    "Trimurti": "TRIMURTI.NS",
    "Trinet Group, Inc.": "TNET.NS",
    "Trinity League": "TRINITY.NS",
    "Triple A": "TRIPLEA.NS",
    "Triveni Engineering & Industries Limited": "TRIVENI.NS",
    "Triveni Turbine Limited": "TRITURBINE.NS",
    "TROPHY": "TROPHY.NS",
    "Tropicana": "TROPICANA.NS",
    "Trout Unlimited": "TU.NS",
    "Tru": "TRU.NS",
    "Truworths International Limited": "TRU.JO",
    "Tube Investments of India Limited": "TIINDIA.NS",
    "Tudor Gold Corp.": "TUD.V",
    "Tumkur": "TUMKUR.NS",
    "Tungabhadra Industries Limited": "TUNGABHADRA.NS",
    "Tungsten Electric Company Limited": "TUNGEL.CO.NS",
    "Turner Construction Company": "TCC.NS",
    "TV Today Network Limited": "TVTODAY.NS",
    "TVS Motor Company Limited": "TVSMOTOR.NS",
    "TVS Srichakra Limited": "TVSSRICHAK.NS",
    "TWL": "TWL.NS",
    "Tyreplex": "TYREPLEX.NS",
    "U P Rajya Vidyut Utpadan Nigam Limited": "UPRVUNL.NS",
    "UCO Bank": "UCOBANK.NS",
    "Uflex Limited": "UFLEX.NS",
    "Ugar Sugar Works Limited": "UGARSUGAR.NS",
    "Ugro Capital Limited": "UGROCAP.NS",
    "Ujaas Energy Limited": "UJAAS.NS",
    "Ultratech Cement Limited": "ULTRACEMCO.NS",
    "Umang Dairies Limited": "UMANGDairy.NS",
    "Umiya Tubes Limited": "UMIYA.NS",
    "Ummeed Housing Finance Private Limited": "UMMEED.NS",
    "Unimech Aerospace and Manufacturing Limited": "UNIMECH.NS",
    "Unimode Overseas Limited": "UNIMODE.NS",
    "Union Bank of India": "UNIONBANK.NS",
    "Unique Construction & Developers Limited": "UNICONST.NS",
    "United Breweries Limited": "UBL.NS",
    "United Drilling Tools Limited": "UNITDRILL.NS",
    "United Health Group Incorporated": "UNH.NS",
    "United India Insurance Company Limited": "UIIC.NS",
    "United Polyfab Limited": "UNITEDPOLY.NS",
    "United Spirits Limited": "MCDOWELL-N.NS",
    "Unity Small Finance Bank Limited": "UNITY.NS",
    "Universal Autofoundry Company Limited": "UNIVASTU.NS",
    "Universal Cables Limited": "UNICABLES.NS",
    "Universal Insurance Company Limited": "UIN.NS",
    "UP Hotel & Resorts Limited": "UPHRL.NS",
    "Uravi T and Wedge Lamps Systems Limited": "URAVI.NS",
    "Urmin Group": "URMINGROUP.NS",
    "Usha Martin Limited": "USHAMART.NS",
    "Usha Martin": "USHAMART.NS",
    "Uttam Galva Metallics Limited": "UTTAMGALVA.NS",
    "Uttam Sugar Mills Limited": "UTTAMSUGAR.NS",
    "Uttaranchal Holiday Resorts Limited": "UHR.NS",
    "Uttaranchal": "UTTARANCHAL.NS",
    "Uttar Pradesh Power Corporation Limited": "UPPCL.NS",
    "Uttam": "UTTAM.NS",
    "V Guard Industries Limited": "VGUARD.NS",
    "V.I.P. Industries Limited": "VIPIND.NS",
    "V2 Retail Limited": "V2RETAIL.NS",
    "Va Tech Wabag Limited": "VATECH.NS",
    "Vaibhav Global Limited": "VAIBHAVGBL.NS",
    "Valiant Laboratories Limited": "VALIANT.NS",
    "Vallum": "VALLUM.NS",
    "Valyoo": "VALYOO.NS",
    "Vanavil Dyes and Chemicals Limited": "VANAVIL.NS",
    "Vandana": "VANDANA.NS",
    "Vantage Corporation": "VANTAGE.NS",
    "Varan London": "VARAN.NS",
    "Varroc Engineering Limited": "VARROC.NS",
    "Vascon Engineers Limited": "VASCONEQ.NS",
    "Vasudha": "VASUDHA.NS",
    "Vaxfab Enterprises Limited": "VAXFAB.NS",
    "VCK": "VCK.NS",
    "Vedant Fashions Limited": "MANYAVAR.NS",
    "Vedanta Limited": "VEDL.NS",
    "Veedol": "VEEDOL.NS",
    "Veer Energy Limited": "VEERENERGY.NS",
    "Veerenergy": "VEERENERGY.NS",
    "Veerenergy": "VEERENERGY.NS",
    "Veerpoint": "VEERPOINT.NS",
    "Veer": "VEER.NS",
    "Veeru": "VEERU.NS",
    "Vejthani": "VEJTHANI.NS",
    "Velan Hotels Limited": "VELANHOTEL.NS",
    "Veljan Denison Limited": "VELJAN.NS",
    "Vellore": "VELLORE.NS",
    "Velox": "VELOX.NS",
    "Vem Technologies Private Limited": "VEMTECH.NS",
    "Venkatesa Mills Limited": "VENMILL.NS",
    "Venky's (India) Limited": "VENKEYS.NS",
    "Venlinad": "VENLINAD.NS",
    "Ven Packing": "VENPACK.NS",
    "Ventura": "VENTURA.NS",
    "Venus Pipes & Tubes Limited": "VENUSPIPES.NS",
    "Venus Power": "VENUSPOWER.NS",
    "Veranda": "VERANDA.NS",
    "Veranda Learning Solutions Limited": "VERANDA.NS",
    "Verde AgriTech Ltd": "NPK.V",
    "Verger": "VERGER.NS",
    "VeriSign, Inc.": "VRSN.NS",
    "Veritas (India) Limited": "VERITAS.NS",
    "Verka": "VERKA.NS",
    "Vermilion Energy Inc.": "VET.TO",
    "Vernova": "VERNOVA.NS",
    "Vertex": "VERTEX.NS",
    "Vertiv Holdings Co": "VRT.NS",
    "Very Good Ventures": "VGV.NS",
    "Very": "VERY.NS",
    "Vesuvius India Limited": "VESUVIUS.NS",
    "Veta": "VETA.NS",
    "Veto Switchgears and Cables Limited": "VETO.NS",
    "Viadeck": "VIADECK.NS",
    "Viacom18": "VIACOM18.NS",
    "Viagold": "VIAGOLD.NS",
    "Viak": "VIAK.NS",
    "Vianet": "VIANET.NS",
    "Viaplay": "VIAPLAY.NS",
    "Vibhor": "VIBHOR.NS",
    "Vicara": "VICARA.NS",
    "Vicis Capital": "VICIS.NS",
    "Vickers": "VICKERS.NS",
    "Vicon": "VICON.NS",
    "Victaulic": "VICTAULIC.NS",
    "Victra": "VICTRA.NS",
    "Vida": "VIDA.NS",
    "Viden": "VIDEN.NS",
    "Vidhi Specialty Food Ingredients Limited": "VIDHIING.NS",
    "Vidya": "VIDYA.NS",
    "Vigil": "VIGIL.NS",
    "Vijaya Diagnostic Centre Limited": "VDL.NS",
    "Vijay Kedia": "VIJAYKEDIA.NS",
    "Vijay Solvex Limited": "VIJAYSOLVX.NS",
    "Vikas Lifecare Limited": "VIKASLIFE.NS",
    "Vikas": "VIKAS.NS",
    "Vikram Solar": "VIKRAMSOLAR.NS",
    "Vikrant": "VIKRANT.NS",
    "Vimta Labs Limited": "VIMTALABS.NS",
    "Vindhya Telelinks Limited": "VINDHYATEL.NS",
    "Vini": "VINI.NS",
    "Vinny": "VINNY.NS",
    "Vinsys": "VINSYS.NS",
    "Vintage": "VINTAGE.NS",
    "Vinyl Chemicals (India) Limited": "VINYLINDIA.NS",
    "Vipul": "VIPUL.NS",
    "Virgo": "VIRGO.NS",
    "Virtusa": "VIRTUSA.NS",
    "Visaka Industries Limited": "VISAKAIND.NS",
    "Vision": "VISION.NS",
    "Vishal Fabrics Limited": "VISHAL.NS",
    "Vishnu Chemicals Limited": "VISHNU.NS",
    "Vishnu": "VISHNU.NS",
    "Vishwas": "VISHWAS.NS",
    "Vistra Corp.": "VST.NS",
    "Vivek": "VIVEK.NS",
    "Vivid": "VIVID.NS",
    "Vivo": "VIVO.NS",
    "VMC": "VMC.NS",
    "Vodafone Idea Limited": "IDEA.NS",
    "Voltas Limited": "VOLTAS.NS",
    "Voron": "VORON.NS",
    "Vow": "VOW.NS",
    "VRL Logistics Limited": "VRLLOG.NS",
    "VST Industries Limited": "VST.NS",
    "VST Tillers Tractors Limited": "VTTL.NS",
    "VTM Limited": "VTM.NS",
    "VXL": "VXL.NS",
    "W.S. Industries (India) Limited": "WSI.NS",
    "Wabag": "VATECH.NS",
    "Wabtec": "WAB.NS",
    "Wade-Gery": "WADEGERY.NS",
    "Wagon": "WAGON.NS",
    "Waaree": "WAAREE.NS",
    "Wabco India Limited": "WABCOINDIA.NS",
    "Wade": "WADE.NS",
    "Wadia": "WADIA.NS",
    "Wago": "WAGO.NS",
    "Walchand": "WALCHAND.NS",
    "Walmart": "WMT.NS",
    "Wanbury Limited": "WANBURY.NS",
    "Wanhui": "WANHUI.NS",
    "Wap": "WAP.NS",
    "Warana": "WARANA.NS",
    "Warner Bros. Discovery, Inc.": "WBD.NS",
    "Warrens": "WARRENS.NS",
    "WashTec": "WSU.DE",
    "Wasteland": "WASTELAND.NS",
    "Waterbase Limited": "WATERBASE.NS",
    "Waterloo": "WATERLOO.NS",
    "Watkins": "WATKINS.NS",
    "Watson": "WATSON.NS",
    "Watts Water Technologies, Inc.": "WTS.NS",
    "Wave": "WAVE.NS",
    "Waves": "WAVES.NS",
    "Waxpol": "WAXPOL.NS",
    "Way2Wealth Brokers Pvt. Ltd.": "WAY2WEALTH.NS",
    "Weal": "WEAL.NS",
    "Wealth": "WEALTH.NS",
    "Wealthy": "WEALTHY.NS",
    "Webel": "WEBEL.NS",
    "Webel Solar Limited": "WEBELSOLAR.NS",
    "Welspun Corp Limited": "WELCORP.NS",
    "Welspun Enterprises Limited": "WELSPUNENT.NS",
    "Welspun India Limited": "WELSPUNIND.NS",
    "Welspun Living Limited": "WELSPUNLIV.NS",
    "Welspun Specialty Solutions Limited": "WSS.NS",
    "Welspun": "WELSPUN.NS",
    "Wendy's Company (The)": "WEN.NS",
    "West Coast Paper Mills Limited": "WSTCSPAPER.NS",
    "West Fraser Timber Co. Ltd.": "WFG.TO",
    "West Life Development Limited": "WESTLIFE.NS",
    "Westcoast Fine Papers Limited": "WESTCOAST.NS",
    "Western Carriers Limited": "WESTCARBAT.NS",
    "Western India Plywood Limited": "WESTIPLY.NS",
    "Western India Shipyard Limited": "WISHLTD.NS",
    "Western Union Company (The)": "WU.NS",
    "Westfield": "WESTFIELD.NS",
    "Westlake Chemical Corporation": "WLK.NS",
    "Westrock Company": "WRK.NS",
    "Wheat": "WHEAT.NS",
    "Wheeler": "WHEELER.NS",
    "Whirlpool of India Limited": "WHIRLPOOL.NS",
    "White": "WHITE.NS",
    "White Organic Agro Limited": "WHITEORG.NS",
    "Whitefield": "WHITEFIELD.NS",
    "Wholesale": "WHOLESALE.NS",
    "Wian": "WIAN.NS",
    "Wichita": "WICHITA.NS",
    "Wickes Group plc": "WIX.L",
    "Wieland": "WIELAND.NS",
    "Wiesbaden": "WIESBADEN.NS",
    "Wigan": "WIGAN.NS",
    "Wildlife": "WILDLIFE.NS",
    "Wiley": "WILEY.NS",
    "Wilhelm": "WILHELM.NS",
    "William": "WILLIAM.NS",
    "Williams": "WILLIAMS.NS",
    "Willis": "WILLIS.NS",
    "Wilmar": "WILMAR.SI",
    "Wilson": "WILSON.NS",
    "Wilton": "WILTON.NS",
    "Wim": "WIM.NS",
    "Wind": "WIND.NS",
    "Windar": "WINDAR.NS",
    "Windsor": "WINDSOR.NS",
    "Wine": "WINE.NS",
    "Wings": "WINGS.NS",
    "Winia": "WINIA.NS",
    "Wipro Limited": "WIPRO.NS",
    "Wipro": "WIPRO.NS",
    "Wiradjuri": "WIRADJURI.NS",
    "Wire": "WIRE.NS",
    "Wisdom": "WISDOM.NS",
    "Wise": "WISE.NS",
    "Wismilak": "WISMILAK.JK",
    "Wipro": "WIPRO.NS",
    "With": "WITH.NS",
    "Wockhardt Limited": "WOCKPHARMA.NS",
    "Wockhardt": "WOCKPHARMA.NS",
    "Woh Hup": "WOHHUP.SI",
    "Wolf": "WOLF.NS",
    "Wolfram": "WOLFRAM.NS",
    "Wood": "WOOD.NS",
    "Woodland": "WOODLAND.NS",
    "Woodward": "WWD.NS",
    "Worley": "WOR.AX",
    "World": "WORLD.NS",
    "Worldline": "WWL.PA",
    "Worm": "WORM.NS",
    "Wort": "WORT.NS",
    "Woven": "WOVEN.NS",
    "WPP plc": "WPP.L",
    "Wro": "WRO.NS",
    "WSL": "WSL.NS",
    "WSP Global Inc.": "WSP.TO",
    "WST": "WST.NS",
    "WTI": "WTI.NS",
    "Wuliangye": "000858.SZ",
    "Wunder": "WUNDER.NS",
    "Wynn": "WYNN.NS",
    "X": "X.NS",
    "Xcel": "XCEL.NS",
    "Xchanging": "XCHANGING.NS",
    "Xel": "XEL.NS",
    "Xelient": "XELIENT.NS",
    "Xenia": "XENIA.NS",
    "Xenon": "XENON.NS",
    "Xerox": "XRX.NS",
    "Xfin": "XFIN.NS",
    "Xinhua": "XINHUA.NS",
    "Xinjiang": "XINJIANG.NS",
    "Xin": "XIN.NS",
    "Xinyi": "XINYI.HK",
    "XPEL": "XPEL.NS",
    "Xperi": "XPER.NS",
    "Xpress": "XPRESS.NS",
    "Xpres": "XPRES.NS",
    "Xpro": "XPRO.NS",
    "XPS": "XPS.NS",
    "XRT": "XRT.NS",
    "XTL": "XTL.NS",
    "Xuande": "XUANDE.NS",
    "Xun": "XUN.NS",
    "Xunlei": "XNET.NS",
    "Y": "Y.NS",
    "Yaan": "YAAN.NS",
    "Yada": "YADA.NS",
    "Yageo": "2327.TW",
    "Yak": "YAK.NS",
    "Yamaha": "YAMAHAMOT.NS",
    "Yamato": "YAMATOHLD.SI",
    "Yancheng": "YANCHENG.NS",
    "Yang": "YANG.NS",
    "Yangzijiang": "BS6.SI",
    "Yankuang": "600188.SS",
    "Yara": "YAR.OL",
    "Yash": "YASH.NS",
    "Yasho": "YASHO.NS",
    "Yatra": "YATRA.NS",
    "Yau": "YAU.NS",
    "Yazaki": "YAZAKI.NS",
    "Yidu": "2159.HK",
    "Yihai": "600105.SS",
    "Yinlu": "YINLU.NS",
    "Yiwu": "YIWU.NS",
    "YKK": "YKK.NS",
    "Yokogawa": "6841.T",
    "Yoma": "Z59.SI",
    "Yon": "YON.NS",
    "York": "YORK.NS",
    "Yoshiharu": "YOSH.NS",
    "Young": "YOUNG.NS",
    "Ypf": "YPF.NS",
    "YRC": "YRCW.NS",
    "YTO": "YTO.NS",
    "Yuanta": "YUANTA.TW",
    "Yue": "YUE.NS",
    "Yuexiu": "123.HK",
    "Yukon": "YUKON.NS",
    "Yum": "YUM.NS",
    "Yun": "YUN.NS",
    "Yungtay": "YUNGTAI.TW",
    "Yunnan": "YUNNAN.NS",
    "Yus": "YUS.NS",
    "Yuz": "YUZ.NS",
    "YVONNE": "YVONNE.NS",
    "Z": "Z.NS",
    "Zaggle": "ZAGGLE.NS",
    "Zaggle Prepaid": "ZAGGLE.NS",
    "Zaggle": "ZAGGLE.NS",
    "Zal": "ZAL.DE",
    "Zall": "ZALL.SZ",
    "Zambian": "ZAMBIAN.NS",
    "Zanat": "ZANAT.NS",
    "Zandu": "ZANDU.NS",
    "Zanskar": "ZANSKAR.NS",
    "Zapp": "ZAPP.NS",
    "Zara": "ZARA.NS",
    "Zee": "ZEEMEDIA.NS",
    "Zee Learn Limited": "ZEELEARN.NS",
    "Zeel": "ZEEL.NS",
    "Zee Media Corporation Limited": "ZEEMEDIA.NS",
    "Zen": "ZEN.NS",
    "Zen Technologies Limited": "ZENTEC.NS",
    "Zenith": "ZENITH.NS",
    "Zenotech": "ZENOTECH.NS",
    "Zensar": "ZENSARTECH.NS",
    "Zest": "ZEST.NS",
    "Zeta": "ZETA.NS",
    "Zhejiang": "ZHEJIANG.NS",
    "Zhong": "ZHONG.NS",
    "Zhongan": "6060.HK",
    "Zhongji": "ZJINNOVT.SZ",
    "Zhongtian": "600583.SS",
    "Zi": "ZI.NS",
    "Zim": "ZIM.NS",
    "Zim Integrated Shipping Services Ltd.": "ZIM.NS",
    "Zinc": "ZINC.NS",
    "Zing": "ZING.NS",
    "Zinnov": "ZINNOV.NS",
    "Zip": "ZIP.NS",
    "Zion": "ZION.NS",
    "Zip2": "ZIP2.NS",
    "Zodiac": "ZODIAC.PA",
    "Zomato": "ZOMATO.NS",
    "Zone": "ZONE.NS",
    "Zota": "ZOTA.NS",
    "Zuari": "ZUARI.NS",
    "Zuventus": "ZUVENTUS.NS",
    "Zydus": "ZYDUSLIFE.NS",
    "Zydus Lifesciences Limited": "ZYDUSLIFE.NS",
    "Zydus Wellness Limited": "ZYDUSWELL.NS",
    "Zynga": "ZNGA.NS"
}
}